Implementation of TimeSlot:endHour parameter, check hour correction methods and check TimeSlots overlapping method
rodi0878/INPTP18-2 pull request #22
Opened 2018-11-29 13:05 UTC by st46567

Hello,
In this pull request I have done following changes in the class "TimeSlot.java":

- Add a paramater "endHour" instead of parameter duration
- Changed parameter name from "hour" to "startHour"
- Add constants "MIN_HOUR" and "MAX_HOUR" to determinate accepted interval for "startHour" and "endHour"
- Add methods "isStartHourCorrect" and "isEndHourCorrect" to check if hour parameters are in accepted interval => these methods are used in a constructor
- Add method "isOverlappingWithOtherTimeslot" to check if two TimeSlots are overlapping

- new tests in the test class "TimeSlotTest.java"

Can you check it please?

Thank you,
Jan Houžvička

2018-11-30 16:57 UTC, bLuma requested changes
There are few issues to discuss and resolve, please see comments

2018-11-30 16:57 UTC, bLuma commented on src/main/java/cz/upce/fei/inptp/zz/entity/TimeSlot.java
> +    private static final int MIN_HOUR = 8;
Do we really need to impose hardcoded limit on hours?

2018-11-30 16:57 UTC, bLuma commented on src/main/java/cz/upce/fei/inptp/zz/entity/TimeSlot.java
> +        if (isStartHourCorrect(startHour)) {
I personally prefer style

if (!check())
  throw ...
if (!check())
  throw 
...
(normal flow continues here)

2018-11-30 16:57 UTC, bLuma commented on src/main/java/cz/upce/fei/inptp/zz/entity/TimeSlot.java
> +    private int endHour = MAX_HOUR;
From startHour, endHour is not clear if both limits are considered as inclusive, exclusive or some combination...

2018-11-30 16:57 UTC, bLuma commented on src/main/java/cz/upce/fei/inptp/zz/entity/TimeSlot.java
> +        return startHour < endHour && startHour >= MIN_HOUR && startHour < MAX_HOUR;
I think that these checks are quite confusing... You're doing check using parameter startHour and also attribute endHour. You're mixing parameters and attributes and method name doesn't imply anything like this. Check for both parameters maybe would be better

2018-11-30 16:57 UTC, bLuma commented on src/test/java/cz/upce/fei/inptp/zz/entity/TimeSlotTest.java
> +    }
Please add also checks for states:
`TA:---XXXX------------------`
`TB:--------------XXXXXX-----`
And also reversed TB-TA.

2018-11-30 19:59 UTC, st46567 commented
Hello,
I tried to resolve issues described in the comments.

Can you check it please?
Thank you.

2018-12-02 17:24 UTC, bLuma approved these changes

2018-12-02 17:24 UTC, merged